### ISSUE TITLE
How to add reducers dynamically and event handlers and states dynamically?

### ISSUE THREAD

**Issue by amit08255** [nanostores/nanostores#106] opened 2022-04-05 09:26 UTC
Please tell me how to add reducers dynamically and event handlers and states dynamically?

I have a page _app which set session in store required by app. Problem is I want to use same store and different page has some different states data. How can I add them dynamically?

**Comment by ai** [comment] 2022-04-05 09:31
The best way in Nano Stores architecture is to use `computed` store for the second page.

Nano Stores is tree shakable state manager. If you use the store only on a single page, the store will be only in page’s bundle.

**Comment by ai** [comment] 2022-04-05 09:31
If you give me a better example, I can show code with more details.

I am closing this issue since it is a question, not a bug.

**Closed by ai** 2022-04-05 09:31 UTC
