### ISSUE TITLE
With map store calling setKey() before subscription loses values

### ISSUE THREAD

**Issue by tivac** [nanostores/nanostores#45] opened 2021-08-04 18:22 UTC
If you use `createMap` to create a map store and update it via `.setKey()` before the store is active it'll dump all those values once it activates.

https://codesandbox.io/s/nanostores-mapsetkey-losing-values-9u0w4?file=/src/index.js

```js
import { createMap, getValue } from "nanostores";

const map = createMap();

map.setKey("foo", 1);
map.setKey("bar", 1);

console.log(getValue(map)); // {}

// Expected it to log out { foo: 1, bar: 1 }
```

It's caused by this condition in `.listen()`,

https://github.com/nanostores/nanostores/blob/d372a5432c9cf875fb59fc3bbe757f40eab5cc30/create-map/index.js#L50-L53

A simple store created via `createStore` doesn't have this extra bit of logic (which makes sense, what would it reset to?)

https://github.com/nanostores/nanostores/blob/d372a5432c9cf875fb59fc3bbe757f40eab5cc30/create-store/index.js#L23-L25

Is this behavior expected/documented anywhere? I didn't expect it to dump all the stored values as soon as something tried to read the values and can't find any info in the readme about it. It *feels* like a bug to me, but I can work around it for now by using `createStore` with a `Map` object and updating it using `update(...)` instead of `.setKey()`.

**Comment by ai** [comment] 2021-08-04 20:51
It is by design. Our stores were created to have logic, and this is why they have two states: active and disabled.

By default, store is in passive form and do not keep value. First subscriber move store to active state.

So you should not set data to disabled store.

What do you think about these changes:
1. Improve docs to explain these differences.
2. Add `createMemoryStore` which will keep data between active and disabled store

**Comment by tivac** [comment] 2021-08-04 20:56
Mentioning it in the docs and throwing an error when writing to a inactive map store is probably enough? I guess the code to check `active` and throw might bump up the library size too much, though it could be a dev-time check.

I don't have a pressing need for something like a `createMemoryStore`, I can use a simple store w/ an object or `Map` easily enough and it'll have broadly the same result for my use-cases. Won't have the per-key diff-checking to prevent superfluous subscriptions but if I need that I can write it in userland. I could also... add a bogus subscription to the store to flip it into active mode I guess? Ugh, that's kinda gross.

**Comment by ai** [comment] 2021-08-04 20:59
> I can use a simple store w/ an object or Map easily enough and it'll have broadly the same result for my use-cases.

Technically, simple store use the same politics of active/disabled stores.

It can remember the state just because we do not need to clean the value (since `set` will replace the value in contrast with partial `setkey` which will lead to forgetting old key cleaning).

**Comment by tivac** [comment] 2021-08-04 21:09
That's fair, I was thinking of these as mostly being a drop-in replacement for svelte stores and in this case they don't match.

Another option I pondered could be that calling `.set`/`.setKey()` on a store it would implicitly flip it to active, since the user intent there seems to be "I'm using this store now"? Dunno, might be too big of a paradigm shift for how the library is designed.

**Comment by ai** [comment] 2021-09-06 23:46
@tivac what you think about this API?

https://gist.github.com/ai/e8b0313b7733d54df15a4ce5499e087d

**Comment by tivac** [comment] 2021-09-07 00:11
Would these be new types named store exports, or a breaking change?

I like the clarity around expectations of value persistence, though IMO even if you want the value to stick around the init/unsub behavior is useful and worth keeping if possible.

**Comment by ai** [comment] 2021-09-07 00:18
@tivac we will keep old names as aliases (and print warning).

> I like the clarity around expectations of value persistence

I want to split functions by function. `deamon*` means that you should use it to put logic inside.

We also can’t use persistence, since only `localStorage` store is a real persistence store. I use `memory*` to notify that page reloading will clean it,

**Comment by ai** [comment] 2021-10-02 17:51
Closed by https://github.com/nanostores/nanostores/pull/62 in next Nano Stores 0.5

Stores will always keep value and developer will mount listeners for specific events

**Closed by ai** 2021-10-02 17:51 UTC
